import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'School Tuition',
    rating: 5,
    ratingCount: 60000,
    price: 500,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'Coding Class',
    rating: 5,
    ratingCount: 55000,
    price: 450,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'Olympiad Tuition',
    rating: 4,
    ratingCount: 45000,
    price: 300,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'Concept Masterclass',
    rating: 4,
    ratingCount: 600000,
    price: 300,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
    title: 'Mental Math',
    rating: 4,
    ratingCount: 80000,
    price: 350,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
    title: 'Foundational Builder',
    rating: 5,
    ratingCount: 50000,
    price: 350,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Exam Preparation',
    rating: 4,
    ratingCount: 70000,
    price:300,
    category: 'Beginner',
  },
]
